<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{

    public function findProjectByKeyword($keyword){

        $query = $this->createQueryBuilder('p')
            ->where('p.nom Like :nom')
            ->setParameter('nom', '%'.$keyword.'%')
            ->orderBy('p.id', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
